### PR TITLE
npm-based custom visualizations (WIP)

### PR DESCRIPTION
**Pull request by mathisonian**
This PR (WIP) enables functionality discussed in #31.

Specifically, it does the following:
* updates the UI of the visualization types page
* defaults to using npm to install custom (and default) visualizations
* simplifies the editor page

The following need to be completed before this can be merged:

- [x] add back-end functional to work with npm
- [x] finish new import visualization modal
- [x] front-end updates to editor page
- [x] add config file to specify npm-based default visualizations
- [x] test preview image importing

--
the following visualizations should also be converted to their own npm-modules before this is merged:
- [x] [adjacency](https://github.com/lightning-viz/lightning-adjacency)
- [x] [force](https://github.com/lightning-viz/lightning-force)
- [x] [gallery](https://github.com/lightning-viz/lightning-gallery)
- [x] [graph](https://github.com/lightning-viz/lightning-graph)
- [x] [graph-bundled](https://github.com/lightning-viz/lightning-graph-bundled)
- [x] [image](https://github.com/lightning-viz/lightning-image)
- [x] [image-poly](https://github.com/lightning-viz/lightning-image-poly)
- [x] [line](https://github.com/lightning-viz/lightning-line)
- [x] [line-streaming](https://github.com/lightning-viz/lightning-line-streaming)
- [x] [map](https://github.com/lightning-viz/lightning-map)
- [x] [matrix](https://github.com/lightning-viz/lightning-matrix)
- [x] [scatter](https://github.com/lightning-viz/lightning-scatter)
- [x] [scatter-streaming](https://github.com/lightning-viz/lightning-scatter-streaming)
- [x] [scatter-3](https://github.com/lightning-viz/lightning-scatter-3)
- [x] [volume](https://github.com/lightning-viz/lightning-volume)

### CODE REVIEW

**Comment by mathisonian** [comment]
I believe this is ready once the remaining viz types are implemented

**Comment by freeman-lab** [comment]
Caught a couple minor glitches probably worth fixing...

- [ ] images not rendering in preview editor (I think just an issue with pulling the sample image data)
- [ ] no warning when deleting a viz (not sure why it's not triggering)

**Comment by colesimmons** [comment]
What is the ETA on this? Looks great!

**Comment by mathisonian** [comment]
Thanks @colesimmons. @freeman-lab and I are getting together this weekend to do final tests and merge it. But I think the branch should more or less stable now if you want to start using it

**Comment by freeman-lab** [comment]
A couple additional issues during testing:

- [ ] css handling within the viz feed for `lightning-scatter` and `lightning-line`
- [ ] clients seem to hang for awhile when asking for a viz that doesn't exist, I don't remember this happening before. is there an endpoint to check the list of existing viz types that the clients could easily ping?

**Pull request merged**
